import dis

def generate_bytecode(source_code):
    print(" Source Code:\n")
    print(source_code)

    print("\n Generated Bytecode:\n")
    compiled_code = compile(source_code, "<string>", "exec")
    dis.dis(compiled_code)


#  Input (multi-line source code)
print("Enter your source code (end with EOF / Ctrl+D):")

lines = []
try:
    while True:
        lines.append(input())
except EOFError:
    pass

source = "\n".join(lines)

generate_bytecode(source)
